[package]
name = "mint-tokens"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.22"
solana-client = "1.18.22"
spl-token = "3.5.0"
dotenv = "0.15"
serde = "1.0"
serde_json = "1.0"
