[package]
name = "send-sol"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.8.2"
solana-client = "1.8.2"
solana-program = "1.8.2"
solana-transaction-status = "1.8.2"
dotenv = "0.15.0"
serde_json = "1.0"