[package]
name = "create-token-mint"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.10.0"
solana-sdk = "1.10.0"
solana-program = "1.10.0"
spl-token = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15"