[package]
name = "create-token-account"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.14"
solana-client = "1.14"
spl-associated-token-account = "1.1"
spl-token = "3.2"
serde_json = "1.0"
dotenv = "0.15"